# Build stage
FROM node:16.18 AS build
WORKDIR /frontend-react-js
COPY . .
RUN npm install && npm run build

# Production stage
FROM node:16.18-alpine
ENV PORT=3000
COPY --from=build /frontend-react-js /frontend-react-js
WORKDIR /frontend-react-js
EXPOSE ${PORT}
RUN ls -la /frontend-react-js
CMD ["npm", "start"]