FROM node:16.18

ENV PORT=3000

COPY . /frontend-react-js
WORKDIR /frontend-react-js
RUN npm install
EXPOSE ${PORT}
# Make npm_start.sh script executable 
RUN chmod +x ./npm_start.sh
ENTRYPOINT ["./npm_start.sh"]
#CMD ["npm", "start"]